# Generated by Django 4.1 on 2022-09-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=128)),
                ('material', models.CharField(max_length=128)),
                ('fillIn', models.CharField(max_length=128)),
                ('is_bed', models.BooleanField(default=False)),
                ('wide', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bed_length', models.IntegerField(blank=True, null=True)),
                ('bed_wide', models.IntegerField(blank=True, null=True)),
                ('bed_height', models.IntegerField(blank=True, null=True)),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mebel_sayt.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mebel_sayt.product')),
            ],
        ),
    ]
