# Generated by Django 4.0.6 on 2023-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel_sayt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_bot',
            field=models.BooleanField(default=True),
        ),
    ]
