# Generated by Django 4.1 on 2022-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_about_me_user_address_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auf',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
