# Generated by Django 4.1 on 2022-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='lang',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='menu',
            field=models.IntegerField(default=0),
        ),
    ]
