# Generated by Django 4.1 on 2022-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_alter_tguser_last_name_alter_tguser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='lang',
            field=models.IntegerField(default=1),
        ),
    ]
