# Generated by Django 4.1 on 2022-09-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_alter_tguser_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='name',
            new_name='first_name',
        ),
    ]
