# Generated by Django 4.1 on 2022-09-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_rename_name_tguser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='user_name',
        ),
    ]
