# Generated by Django 4.1 on 2022-09-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_remove_tguser_first_name_remove_tguser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='lang',
            field=models.IntegerField(null=True),
        ),
    ]
